// ------------------------------------------------------------------------------
// <auto-generated>
//     Not really auto-generated, but easier than supressing rules manually...
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Spectre.Terminals.Drivers
{
    internal sealed partial class MacOSInterop
    {
        public struct termios
        {
            public UIntPtr c_iflag;
            public UIntPtr c_oflag;
            public UIntPtr c_cflag;
            public UIntPtr c_lflag;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = NCCS)]
            public byte[] c_cc;
            public UIntPtr c_ispeed;
            public UIntPtr c_ospeed;
        }

        public struct winsize
        {
            public ushort ws_row;
            public ushort ws_col;
            public ushort ws_xpixel;
            public ushort ws_ypixel;
        }

        [DllImport("libc")]
        public static extern int tcgetattr(int fd, out termios termios_p);

        [DllImport("libc")]
        public static extern int tcsetattr(int fd, int optional_actions, in termios termios_p);

        [DllImport("libc")]
        public static extern int ioctl(int fildes, UIntPtr request, out winsize argp);
    }
}
